// <auto-generated />
namespace LeagueApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addmigration1118201330 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmigration1118201330));
        
        string IMigrationMetadata.Id
        {
            get { return "202011181831016_add-migration 1118201330"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
