// <auto-generated />
namespace LeagueApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class BeforeUpdateCoachDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BeforeUpdateCoachDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202011162150298_BeforeUpdateCoachDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
