// <auto-generated />
namespace LeagueApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _11232012333 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11232012333));
        
        string IMigrationMetadata.Id
        {
            get { return "202011231723097_11232012333"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
